//gallery items: leashes, collars, toys, treats, bones, park locations, clothing, food, poop bags, beds, dog tags, medication
 const dogStuff = [
    {
      id: 1,
      name: leashes,
      description:  ,
      imgURL: ,
      width: ,
      height: ,
    },
    {
      id: 2,
      name: collars,
      description: ,
      imgURL: ,
      width: ,
      height: ,
    },
    {
      id: 3,
      name: toys,
      description: ,
      imgURL: ,
      width: ,
      height: ,
    },
    {
      id: 4,
      name: treats,
      description: ,
      imgURL: ,
      width: ,
      height: ,
    },
    {
      id: 5,
      name: bones,
      description: ,
      imgURL: ,
      width: ,
      height: ,
    },
    {
      id: 6,
      name: park-locations,
      description: ,
      imgURL: ,
      width: ,
      height: ,
    },
    {
      id: 7,
      name: clothing,
      description: ,
      imgURL: ,
      width: ,
      height: ,
    },
    {
      id: 8,
      name: food,
      description: ,
      imgURL: ,
      width: ,
      height: ,
    },
    {
      id: 9,
      name: poop-bags,
      description: ,
      imgURL: ,
      width: ,
      height: ,
    },
    {
      id: 10,
      name: beds,
      description: ,
      imgURL: ,
      width: ,
      height: ,
    },
    {
      id: 11,
      name: dog-tags,
      description: ,
      imgURL: ,
      width: ,
      height: ,
    },
    {
      id: 12,
      name: medication,
      description: ,
      imgURL: ,
      width: ,
      height: ,
    },
 ]
  
